// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.bp.netty.protoc;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bp.netty.proto.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_info = 1;</code>
   */
  String getRequestInfo();
  /**
   * <code>string request_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();
}
